name: Install clang
description: Install clang tidy and clang-format given a specified version

inputs:
  version:
    description: The version of clang tools to install
    required: true

runs:
  using: composite
  steps:
    - name: Install Linux clang dependencies
      if: runner.os == 'Linux'
      shell: bash
      env:
        CLANG_VERSION: ${{ inputs.version }}
      # NOTE: sudo apt-get update should be executed at least once before running this action
      run: |
        # First try installing from default Ubuntu repositories before trying LLVM script
        if ! sudo apt-get install -y clang-format-${CLANG_VERSION} clang-tidy-${CLANG_VERSION}; then
          if [ ! -f "${{ runner.temp }}/llvm_install.sh" ]; then
            # This LLVM script will add the relevant LLVM PPA: https://apt.llvm.org/
            wget https://apt.llvm.org/llvm.sh -O ${{ runner.temp }}/llvm_install.sh
            chmod +x ${{ runner.temp }}/llvm_install.sh
          fi
          if sudo "${{ runner.temp }}/llvm_install.sh" "${CLANG_VERSION}" ; then
            sudo apt-get install -y clang-format-${CLANG_VERSION} clang-tidy-${CLANG_VERSION}
          fi
          # remove the PPA for future reuse of install script (regardless of successful install)
          sudo rm /etc/apt/sources.list.d/*llvm*.list || true
        fi

    - name: Install MacOS clang dependencies
      if: runner.os == 'macOS'
      shell: bash
      continue-on-error: true
      env:
        CLANG_VERSION: ${{ inputs.version }}
      run: |
        brew update
        brew install llvm@${CLANG_VERSION}
        ln -s "$(brew --prefix llvm@${CLANG_VERSION})/bin/clang-format" "/usr/local/bin/clang-format-${CLANG_VERSION}"
        ln -s "$(brew --prefix llvm@${CLANG_VERSION})/bin/clang-tidy" "/usr/local/bin/clang-tidy-${CLANG_VERSION}"
    - name: Use clang-tools-pip as fallback
      shell: bash
      env:
        CLANG_VERSION: ${{ inputs.version }}
      run: |
        python -m pip install clang-tools
        clang-tools -i ${CLANG_VERSION} -b -f
