name: Install clang
description: Install clang tidy and clang-format given a specified version

inputs:
  version:
    description: The version of clang tools to install
    required: true

runs:
  using: composite
  steps:
    - name: Install Linux clang dependencies
      if: runner.os == 'Linux'
      shell: bash
      # NOTE: sudo apt-get update should be executed at least once before running this action
      run: |
        # First try installing from default Ubuntu repositories before trying LLVM script
        if ! sudo apt-get install -y clang-format-${{ inputs.version }} clang-tidy-${{ inputs.version }}; then
          if [ ! -f "${{ runner.temp }}/llvm_install.sh" ]; then
            # This LLVM script will add the relevant LLVM PPA: https://apt.llvm.org/
            wget https://apt.llvm.org/llvm.sh -O ${{ runner.temp }}/llvm_install.sh
            chmod +x ${{ runner.temp }}/llvm_install.sh
          fi
          if sudo "${{ runner.temp }}/llvm_install.sh" "${{ inputs.version }}" ; then
            sudo apt-get install -y clang-format-${{ inputs.version }} clang-tidy-${{ inputs.version }}
          fi
          # remove the PPA for future reuse of install script (regardless of successful install)
          sudo rm /etc/apt/sources.list.d/*llvm*.list || true
        fi

    - name: Install MacOS clang dependencies
      if: runner.os == 'macOS'
      shell: bash
      continue-on-error: true
      run: |
        brew update
        brew install llvm@${{ inputs.version }}
        ln -s "$(brew --prefix llvm@${{ inputs.version }})/bin/clang-format" "/usr/local/bin/clang-format-${{ inputs.version }}"
        ln -s "$(brew --prefix llvm@${{ inputs.version }})/bin/clang-tidy" "/usr/local/bin/clang-tidy-${{ inputs.version }}"

    - name: Use clang-tools-pip as fallback
      shell: bash
      run: |
        python -m pip install clang-tools
        clang-tools -i ${{ inputs.version }} -b -f
