name: Pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  pre-commit:
    permissions:
      contents: read
    uses: cpp-linter/.github/.github/workflows/pre-commit.yml@main

  cargo-tools:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - run: rustup update
      - name: Cache .cargo locked resources
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: cargo clippy
        run: cargo clippy -- -D warnings
      - name: cargo fmt
        run: cargo fmt --check

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
      - run: yarn install
      - run: yarn lint
